### ISSUE TITLE
Highlight active day nicer in Calendar+:

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#104]
Highlight active day nicer in Calendar+:
See screenshot: Idea based on Baikal2 development: See demo here: http://baikal2.scalingo.io/login
![day highlited](https://cloud.githubusercontent.com/assets/3358665/9354784/339835c0-466b-11e5-800f-cebafd9d836d.png)

Idea based on Baikal2 development: See demo here: http://baikal2.scalingo.io/login

**Comment by joeplus** [comment]
Since i think in owncloud we don't have bubbles the only way this could work is to color the rectangle with the date on top in a different background color, leave the text white and remove the background color from the actual day.

**Comment by Bullnados** [comment]
@joeplus :+1:
