### ISSUE TITLE
Show overlapping events more nicely.

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#105]
Idea based on Baikal2 development: See demo here: http://baikal2.scalingo.io/login

Screenshot: It appears it is possible to show overlapping events slightly nicer. Thats a suggestion:
![nicer overlap of events](https://cloud.githubusercontent.com/assets/3358665/9355074/9514012e-466d-11e5-83bf-0d67dc39a3e1.png)

At present in my opinion Calendar+ pushes the overlapping event too much to the right, eating up some info.  Also based on above scrrenshot, some transparency would be handy...

![bad overlap](https://cloud.githubusercontent.com/assets/3358665/9355078/98c7a370-466d-11e5-9f6a-0a5dec480815.png)

**Comment by Bullnados** [comment]
I confirm with you thats too much to the right, and time info get lost. But no tranceparency like in baikal. Test text shows through top events I think thats confusing.

**Comment by joeplus** [comment]
I honestly think that the Baikal implementation is inferior to what is there now. As @Bullnados said the transparency makes it hard to read and if you have more than two appointment it is just very confusing!

**Comment by libasys** [comment]
at the moment it is not possible to change the behaviour, this behaviour comes from fullcalender script self!
