### ISSUE TITLE
[event creation outside of display area the second

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#106]
Might be related to https://github.com/libasys/calendarplus/issues/22
![event creation outside of display area 1](https://cloud.githubusercontent.com/assets/3358665/9355208/d314afcc-466e-11e5-8665-dedf5342ab53.png)

Using Firefox browser.
If an event is created, in some circumstances the creation mask appears outside of screen. This makes handling difficult for users and should be improved. Can be reproduced on https://ssl.webpack.de/demo81.libasyscloud.de/index.php/apps/calendarplus/?

**Comment by libasys** [comment]
This could happend, cause this is a 3rdparty lib, but i hope it not happens very often! but if is time then i investigate some more!
