### ISSUE TITLE
no birthday support?

### ISSUE THREAD

**Issue by ShinyShrimp** [libasys/calendarplus#109]
Hi,

I'm using version 1.0.2 but birthdays from contacts app are not shown. What can I do?

**Comment by Bullnados** [comment]
Are you using contactplus or normal shipped contact app?

**Comment by ShinyShrimp** [comment]
yep calendarplus and contactsplus

**Comment by ShinyShrimp** [comment]
hm now its working O_o

**Comment by Berni-MD** [comment]
In my calendar the birthdays are missing :-(
Does anyone have an idea what is going wrong here?

**Comment by Berni-MD** [comment]
Oh shit - who can read is a clear advantage!
The old contact app is no disabled, and all birthdays are displayed! :-)
