### ISSUE TITLE
 Updates / bugfixes of your app? How can an admin maintain?

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#11]
@libasys After one has installed your app, how will new updates / bugfixes of your app be pushed onto running instances?
That's pretty important. Please do explain or/and add to documentation (I am happy to translate into English :-).

**Comment by libasys** [comment]
Hi @farson2003, if a new version of calendarplus is available and stable, than i will upload the new zip file to the appstore! Can be found here: https://apps.owncloud.com/content/show.php/Calendar+Plus?content=170560 ! If the calendarplus update is not well tested and not stable, it is possible to download the current master for testing on a test environement! And on the changelog of the appstore you can see what happend on the update!

**Comment by farson2003** [comment]
THank you.
@libasys wrote "...if a new version of calendarplus is available and stable, than i will upload the new zip file to the appstore! Can be found here: https://apps.owncloud.com/content/show.php"

Does one simply Unzip such new version into the app folder of the old version?
Should the old version+folder be completly deleted prior to uploading the new version to the running OC instance?

It would be really helpful to have some safe documnetation on how to update to avoid data loss or data corruption in a running production instance with many users...
THank you!

**Comment by javaboyuk** [comment]
HI Libsys. What happens say if you upload a new version of your app, BUT it requires a chnage in the database layout for example... or some over general change that means two things, one how do you upgrade the data base. Second you cant JUST go back with out a down-grade script. I think that is what farson2003 is also asking.

**Comment by farson2003** [comment]
Hello @libasys, what @javaboyuk and myself are trying to convey is:
It is really crucial to have a very well documented and safe update/upgrade procedure of your app.
The worst thing that could happen if admins start implementing calendar+ instead of owncliud's native app is that an update corrupts the system and many users find their previous calendar+ calendars unusable and/or data lost.
Such scenario would lead to only one conclusion if I work as an admin: Never use calendar+ it again, even if it is brilliant otherwise.

In order to prevent this from happening, we all ask for exact info on how to safely implement future updates of your app.
