### ISSUE TITLE
Imported or synced events are not editable because of reminder settings

### ISSUE THREAD

**Issue by deMattin** [libasys/calendarplus#110]
If you set reminders on a caldav synced smartphone or import calendars there are some entries not editable.
The Problem is a reminder, that is set up for just in time of the event.
There is an active reminder symbol shown in callendarplus but without a time specified.
If you set the reminder to 1 Minute before event on Smartphone and resync, the entry becomes editable in calendarplus owncloud webapp.
1. just in time should be possible in calendarplus
2. all different flags in synced data (P0...) with only "0" (0 Minutes, 0 hours, ...) should be recognized as in time of event (0 Minutes) and not being ignored if calendarplus couldn't interpret it.
3. no "wrong" or by the app not understanded setting in synced data should prevent editing

**Comment by libasys** [comment]
at the moment this is the default behaviour that P0 get ignored!

**Comment by deMattin** [comment]
OK, but will be fixed sometime?
For now it is a workaround, only to use reminders > +- 1 Minute of event

**Comment by libasys** [comment]
@deMattin can you paste an event with this reminder settings for debugging and a workaround that this event keeps editable!

**Comment by deMattin** [comment]
As it is not possible to edit the "just-in-time" Alarm event in cal+, I had to export the calendars from the synced lightning calendar and out of DB.
But if you import them in cal+ you see, that they are not editable.

Created in Thunderbird/Lightning as 1 Day event and "just in time alarm" and synced to calendar+:

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20150825T193830Z
LAST-MODIFIED:20150825T193855Z
DTSTAMP:20150825T193855Z
UID:5bbb37bb-9e90-4ea5-bb47-ce89bd3cf7b9
SUMMARY:Test-0-ALARM
DTSTART;VALUE=DATE:20150826
DTEND;VALUE=DATE:20150827
TRANSP:TRANSPARENT
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:PT0S
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM
END:VEVENT
END:VCALENDAR
```

Created in Android Phone as 1 Day event with "just in time alarm" -> synched -> readout DB -> imported in calendar+ (I have deactivated sync adapter for calendar+ so I had to go this way):

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//bitfire web engineering//DAVdroid 0.8.3 (ical4j 2.0-alpha1)//EN
BEGIN:VEVENT
DTSTAMP:20150825T191439Z
UID:20150825T191439Z-2087_42d7ad27b56d4441
DTSTART;VALUE=DATE:20150827
DTEND;VALUE=DATE:20150828
SUMMARY:Test-0-Alarm
STATUS:CONFIRMED
ORGANIZER:mailto:mail@mail.de
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Test-0-Alarm
END:VALARM
END:VEVENT
END:VCALENDAR
```

My "workaround" simply means to set only alarm times <> 0 in the other synced apps (or to say: don't use "just in time" alarms).
Setting it to 1 minute before as an example is displayable, editable and creatable (as custom) in calendar+.

So my proposal has been to interprete a PT0S or PT0M as a "just in time Alarm" (here both apps created "PT0S" but I think, "PT0M" could also be possible.

And it should be possible to set a just in time alarm also in calendar+.

In some calendars it's also possible to set 30 seconds before. So "seconds" (PTxS) has also to be interpreted by calendar+.
I don't see a need of this to be setable in calendar+, but it has to be shown and the event has not to be prevented from editing.

Is this information sufficent enough or do you need more or should I test more?

**Comment by libasys** [comment]
Yes it is! Thanks! I will have a look the days!

**Comment by libasys** [comment]
ok i have done a workaround, to fix this issue! if the reminder reader detects time = 0 it interprets it as "just in time" reminder! comes with 1.0.6

**Comment by libasys** [comment]
fixed in current master 1.0.6

**Comment by deMattin** [comment]
@libasys: Editing is no more blocked. So main issue is fixed.

In popup of my Test-0-Alarm the alarm is shown as "Could not read Alarm".
But if you go in edit, you see text "just in time". So it seems just to be an issue in showing this just in time Alarm in popup.
If you set a 0s or 0m alarm in cal+, it's always shown correct. Only the imported alarm has this "could not read" showing.
The difference seems to be, that a "-PT0S" or "-PT0M" is used, if Alarm is set in cal+ and the "PT0S" or "PT0M" of imported alarm events.

So you should simply interprete also "PT0..." additional to "-PT0..." as just in time and not "Could not read"..

And I think, it should also be setable:
- "0" in this arrow selectable time
- and a preset "0 minutes", "0 seconds"  or "Just in time" additional to "5 minutes", "10 minutes", ...
  If you stay on using wording "just in time" (it's a bit unusual, but I like it) and not 0 minutes, the setable preset should also be named like that.

The lack of some german translation will surely be fixed later.

And I see a sorting issue for custom alarms. Weeks before and after is at the bottom of the list but other alarm presets are sorted first before (seconds, minutes, hours, days) and then after.

All this are only small issues - you are working hard on it right now. Thanks!

**Comment by deMattin** [comment]
Tested and:
- confirmed as working for "-PT0..." as "just in time"
- confirmed (german) translation
- confirmed sorting "week" in customized alarm
- **not confirmed** selectable preset for "just in time event"
- **not confirmed** "arrow selectable "0" value with this arrows
  (not needed, if a preset for just in time is there)

Don't you like to give a quick selectable preset for "just in time" or "0 minutes" (which would probably look better because following there are 5, 10, 15, ... minutes presets)?

I think, it's not a really rare usecase.
Around 50% of my reminders are set like this as "just in time". ;)
