### ISSUE TITLE
[enhancement] Address / location completion with data of contacts

### ISSUE THREAD

**Issue by deMattin** [libasys/calendarplus#111]
I really miss the automatic address completion like in the yet "official" contacts app.
So if you begin typing an address in location of event, calendarplus app should search in contactsplus app for fitting addresses.

The next enhancement step could be an additional search in previous events.
So this way you don't have to type same data again, if you have set a place in contacts or in an earlier defined event.

**Comment by libasys** [comment]
comes with next commit on master! i think tommorow, if nothing happens!

**Comment by deMattin** [comment]
:+1: 
And it's very nice, that this works with contacts+ **and** with oc official contacts!
Also the full text search is a nice feature. So it's possible to search on contact's name and get the address of this contact!

**Comment by libasys** [comment]
have you tested the global search (header bar) with the nice popover opening with all information of a contact? this is really cool!

**Comment by deMattin** [comment]
Yes, I've seen and forgotten to mention ... ;)
Really, really nice!
