### ISSUE TITLE
Deleting standard (default) calendar prevents creation of events

### ISSUE THREAD

**Issue by deMattin** [libasys/calendarplus#112]
If you delete the actual default or standard calendar, it is not possible any more to create new events.
Clicking in the calender doesn't show the "create new event" box.
The creation dialog depends on the default calender and isn't shown, if there is none defined.

So there are two solutions if you delete the marked standard calendar, I think:
1. give another / the next / a random calendar the standard-flag and also check it graphically.
2. force the user to select a default / standard calendar first, if the user clicks in event section to create a new event with a message "Please select a default calendar first" or something like that.

I would personally prefer solution 1 because it is simpler and more pragmatic ...

**Comment by libasys** [comment]
will be fixed with next version! (1.0.5 or later)

**Comment by deMattin** [comment]
Ok, you fixed it with 1.0.5 but now there is the issue, that the default calender is reset on every reload or restart of calendar to the first (alphabetical top most) calendar.
The default calendar should be saved.

**Comment by libasys** [comment]
fixed in current master

**Comment by deMattin** [comment]
Seems not to be fixed.
It's always the first calendar in list, that is defalt after calendar+ reload!

**Comment by libasys** [comment]
I think the behaviour of current master is ok, the default calendar get loaded if is no calender is found!

**Comment by deMattin** [comment]
May be, we misunderstood.
Steps to reproduce:
1. I have more than 1 (in my case 6) calendars active. Calendars are sorted alphabetical.
2. I select another calendar (2nd, 3rd, or whatever) as default calendar (check on color)
3. reload calendar+  -> the first calendar in list now is selected as default calendar

I think, the last as default checked calendar should be saved as default and it should not be reset to first calendar in list after reload or next start of calendar+.

**Comment by libasys** [comment]
fixed in current master thanks for the bug report!

**Comment by deMattin** [comment]
confirmed for working!
