### ISSUE TITLE
Calendar timezones are not working correctly when syncing to Android via Caldav

### ISSUE THREAD

**Issue by JonathanCrouse** [libasys/calendarplus#113]
Using the New York (-0400) time zone, the web interface always shows as 4 hours ahead of the same time that is shown on the Android calendar.  For example, when creating an event for 10:00 am via the web interface, it will sync to android calendar and show as 6:00 am.  The android app timezone is Eastern Daylight Time GMT-4.

**Comment by deMattin** [comment]
I'm not able to confirm this for contactsplus but have a similar issue with birthday calendar of official calendar app.
There a birthday also has a time preset issue that seems to be related to UTC not being properly set to local timezone in android and so there is a birthday from 1am til 1am of following day and so lasts for 2 days - but only in german daylight saving time and only for birthdays!
And this events are also marked with UTC and local time in android calendar (you are able to see both times in detail or edit view).

This is a new issue for me without any changes in official owncloud calendar app and so maybe it is an issue related with the sync app?
I use actual davdroid.

**Comment by JonathanCrouse** [comment]
deMattin, I think you're right.  I set up CalDAV Sync Adapter and the times are correct when using that app.  Seems to be something with DavDroid.  Not sure why mine is off by four hours though.  Thanks.

**Comment by deMattin** [comment]
I also tested the actual development branch of this sync adapter (aCalDAV) https://github.com/ennswi/AndroidCaldavSyncAdapater but sadly it didn't fix my issue with contacts birthdays in "official" contacts app https://github.com/owncloud/contacts/issues/1029
But it's a good thing, that it did help to fix your problem and now I know, that my problem probably isn't related to the used caldav sync adapter.
