### ISSUE TITLE
Enhancement Request - Option to Show Date as mm/dd/yy

### ISSUE THREAD

**Issue by MNOCFan** [libasys/calendarplus#116]
If there is any way, for us Americans, it would be a wonderful thing to have an option to set the dates as Month-Day-Year. We are easily thrown off by the Day-Month-Year format. :)

**Comment by jancborchardt** [comment]
This should automatically be handled from the language and not be a separate option (similar for first day of the week and time format). I believe moment.js has a means of doing that automatically? @Pvince81

**Comment by libasys** [comment]
i have added a settings option we need some secure parsing methods for checking if the date is valid!
is in master version 1.0.5! all for our american friends! ;)

**Comment by MNOCFan** [comment]
@libasys This is working great! I speak for all americans when I say thank you! :)

**Comment by jancborchardt** [comment]
@libasys can we automatically check this from the language? The settings are already full as they are :\

**Comment by libasys** [comment]
Not at the moment, it is a problem of the parsing rules of a date, so if it is in the settings i have a secure pattern to search for correct date placement like day month year!
