### ISSUE TITLE
appointments not displayed

### ISSUE THREAD

**Issue by Mr-HeBo** [libasys/calendarplus#117]
Hello, 

my appointments which are planned after 05.09.15, are not displayed in my ownCloud (daily, weekly, monthly ... all views). On my mobile devices everything is ok.

![cloud](https://cloud.githubusercontent.com/assets/11228598/9468460/105a1156-4b42-11e5-8cb9-c3ed12988507.png)
![mobile](https://cloud.githubusercontent.com/assets/11228598/9468469/1c2ad9de-4b42-11e5-9405-d51a426bd282.png)

regards

OnCloud 8.1.1 shared hosts
calendarplus 1.0.4

**Comment by libasys** [comment]
please update your app to current master 1.0.5, this should be fixed!

**Comment by Mr-HeBo** [comment]
thx! Now it works fine :)
