### ISSUE TITLE
1.0.5 - No Controls for Next/Previous Month When in Full Screen View

### ISSUE THREAD

**Issue by MNOCFan** [libasys/calendarplus#121]
When viewing in full screen mode (left menu hidden) there are no controls for advancing to the next or previous month.

**Comment by MNOCFan** [comment]
In addition to this, there should be a "Today" button.

**Comment by libasys** [comment]
fixed in current master 1.0.6

**Comment by MNOCFan** [comment]
VERY NICE! Thank you for this addition.
