### ISSUE TITLE
Event titles are cropped for 45min events

### ISSUE THREAD

**Issue by pravussum** [libasys/calendarplus#122]
See attached screenshot
![event_names_cropped](https://cloud.githubusercontent.com/assets/5208777/9492066/786fec40-4bf4-11e5-83c8-f62811c3ef29.PNG)

The event time and title should be an one liner like it is done for 30 minute events.

**Comment by pravussum** [comment]
Using 1.0.3 btw.

**Comment by libasys** [comment]
that is the default behaviour of fullcalendar script (3rd Party)
