### ISSUE TITLE
1.0.3 Agenda events in day view not sorted

### ISSUE THREAD

**Issue by pravussum** [libasys/calendarplus#123]
One would expect the events in the agenda (daily view) to be sorted by begin time, but they seem to be unsorted.

**Comment by pravussum** [comment]
By the way: I don't understand how scrolling to the selected day works. The selected days events are neither on top of the list nor at the bottom, but kind of in the middle. This is counter intuitive as well... 
I would only expect this kind of behaviour if the list is not long enough and fully scrolled down, but this was not the case.

**Comment by libasys** [comment]
fixed with current master version 1.0.6! Thanks for your bug report!

**Comment by pravussum** [comment]
Perfect, works, thx a lot.
