### ISSUE TITLE
Bug: Shared calendar events cannot be edited.

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#126]
Steps to reproduce:
1.  Administrator of group X shares calendar “test” with group X. 
2.  Administrator of group X creates event Z in calendar "test".
3.  User XY, a member of group X, logs on and clicks on event Z in calendar “test” which was shared by the administrator to group X.
4.  When user XY clicks on “edit” to edit event Z, and then changes the event title, and then clicks “OK” nothing happens.
5.  Also when user XY clicks on “Delete” to delete event Z, a popup “Delete event “undefined” Are you sure" appears, but clicking Yes has no effect.

Version 1.0.6, OC 8.1.1

**Comment by libasys** [comment]
problem is fixed! Thanks for your bug report
