### ISSUE TITLE
Wrong position of "event-edit-popup" in 1.0.4

### ISSUE THREAD

**Issue by BADF00D** [libasys/calendarplus#127]
First of all I created a event that last from Saturday to Sunday. Clicking on the part that is on Sunday, everything is ok. But clicking on the part that is on Saturday, the "event-edit-popup" is at the button, outside the calendar, so I have to scroll down.

**Comment by libasys** [comment]
Have you tested the current master version 1.0.6 there are some improvements with placement of popovers?

**Comment by BADF00D** [comment]
I just updated to 1.0.7. The previous error is solved, but a new one seems to be introduced. Same situation as before. I create an event from Saturday 14:00 20th February to Sunday 17:00 21th February 2016.

When I click anywhere on the event that is on Saturday, everything works as expected, as the next screenshot shows:

![screen1](https://cloud.githubusercontent.com/assets/2852160/9590266/dd4ec8f0-5033-11e5-9f04-41a0bdd46273.jpg)

When I position the screen like the next screenshot shows an click on Saturday nothing happens.

![screen2](https://cloud.githubusercontent.com/assets/2852160/9590272/e9413846-5033-11e5-9060-a6138e7211a7.jpg)

When I now scroll to 00:00 and then click at Saturday, the popup is shown correctly and event when I scroll down the popup stays correctly, as next screenshot shows:

![screen3](https://cloud.githubusercontent.com/assets/2852160/9590277/f0f2a9a8-5033-11e5-8b9e-6c00734d904d.jpg)
