### ISSUE TITLE
layout issue on calendarplus 1.0.6

### ISSUE THREAD

**Issue by ernesst** [libasys/calendarplus#129]
hello,

After launching the latest release i found a layout bug.

Please see the picture enclosed
![2015-08-27 08_53_38-calendar - owncloud](https://cloud.githubusercontent.com/assets/11337464/9514305/2fc48e2e-4c99-11e5-8bb1-a9040a16cf54.png)

It seems an interference with  Direct Menu 0.3

Regards
Kevin

**Comment by deMattin** [comment]
Yes, a bug in a not official menu hack using the header ... ;)
Should be closed her, because double of #124
