### ISSUE TITLE
Update to 1.0.6 breaks the ownCloud files app

### ISSUE THREAD

**Issue by Visual-Notes** [libasys/calendarplus#130]
After updating Calendar+ from the app updater to version 1.0.6, the ownCloud files app doesn't work anymore. All i get is a blank page, i have no access to my files. Other apps like Calendar+, RainLoop, Gallery etc. are working normally. The reason why i actually get access to the other apps is the fact that i have defined Calendar+ as default app.

**Comment by libasys** [comment]
hi @africanforest thanks for your bug report, please give me some more information about enviroment active apps etc? what says the error log on the admin settings page? what happends if you deactivate calendar+ app? Thanks!

**Comment by Visual-Notes** [comment]
Sorry, i forgot to add the error log:

Error   PHP RuntimeException: The source file "/home/.sites/web/cloud/apps/calendarplus/js/3rdparty/jquery.miniColors.min.js" does not exist. at /home/.sites/web/cloud/3rdparty/kriswallsmith/assetic/src/Assetic/Asset/FileAsset.php#62  
Error   calendarplus    Could not find resource file "/cloud/apps/calendarplus/js/3rdparty/jquery.miniColors.min.js"  
Fatal   index   RuntimeException: The source file "/home/.sites/web/cloud/apps/calendarplus/js/3rdparty/jquery.miniColors.min.js" does not exist.  
Error   calendarplus    Could not find resource file "/cloud/apps/calendarplus/js/3rdparty/jquery.miniColors.min.js"    

---

Additional active apps are:
bookmarks, calendarplus, contacts, galleryplus, logreader, pinit, rainloop, tasksplus.

Encryption is not activated.

**Comment by libasys** [comment]
confirmed

**Comment by libasys** [comment]
fixed in current master!

**Comment by Visual-Notes** [comment]
Thank you for fixing that issue so quickly! Everything works perfectly now.

**Comment by libasys** [comment]
thanks for your bug report!
