### ISSUE TITLE
version 1.0.6 collides with direct menu plugin

### ISSUE THREAD

**Issue by ShinyShrimp** [libasys/calendarplus#131]
I like the direct menu plugin very much because, I can change owncloud apps with one click instead of two. So is it possible to change css to to keep calendar+ compatible with direct menu plugin?

![image](https://cloud.githubusercontent.com/assets/11614619/9518873/9fb05ad0-4cba-11e5-958a-5ecbdeed2c0e.png)

**Comment by deMattin** [comment]
Sorry, is it so hard to read already opened issues? You are opening the third issue for this!
And git also has a search function, that finds both here "direct menu" or "direct menu".
see: #124  (and #129)
It's an issue to be solved in the other app and not in calendar+.

**Comment by ShinyShrimp** [comment]
sorry man, I'll search first next time.
