### ISSUE TITLE
After closing? event sometimes a "bubble" remains

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#134]
I am not sure when it happens exactly, and it happens only rare.
However sometimes after doing something with an event and then closing it a "bubble" remains.

Not sure how I can help to get to the source of the problem....
![remaining bubble](https://cloud.githubusercontent.com/assets/3358665/9557131/64d417a4-4dd1-11e5-88d6-ea6f7ceaeab4.png)

**Comment by libasys** [comment]
fixed!
