### ISSUE TITLE
1.0.7 - Calendar subscriptions seem buggy

### ISSUE THREAD

**Issue by MNOCFan** [libasys/calendarplus#140]
In my environment I tried adding this calendar subscription (NCAA FB Alabama Crimson Tide):
https://www.google.com/calendar/htmlembed?src=ncaaf_73_%2541labama%2B%2543rimson%2B%2554ide%23sports%40group.v.calendar.google.com&ctz=America/Chicago
- After adding it, it gave me a message in a foreign language that looked to maybe say it was successful. I can't be sure.
- Calendar did not immediately appear in calendar list under subscriptions until I refreshed the screen.
- After refreshing screen, calendar appeared but no events can been seen or no events seem to have been imported.
- Options for newly subscribed calendar are not accessible to delete calendar.
- End result, this calendar is stuck in my subscription list.

**Comment by libasys** [comment]
This calendar is only for sharing within google, tested also on a desktop calendar client! get error message also!

**Comment by MNOCFan** [comment]
@libasys Understood! Thank you for checking this out. I thought those links in Google were supposed to be publicly linkable to any calendar, but it has proven to not be.
