### ISSUE TITLE
Default calendar is reset on page reload

### ISSUE THREAD

**Issue by pravussum** [libasys/calendarplus#142]
Whenever I reload the page, the default calendar is reset to (I suppose) the first calendar in the lefthand list. The "wrong" default calendar is also suggested in the new event dialog etc...

**Comment by pravussum** [comment]
Using current master / 1.0.8.

**Comment by deMattin** [comment]
https://github.com/libasys/calendarplus/issues/112#issuecomment-135833301

**Comment by libasys** [comment]
fixed in current master! thanks for reporting!

**Comment by deMattin** [comment]
confirmed for working
