### ISSUE TITLE
http 401 when tryin got use shared calender via URL

### ISSUE THREAD

**Issue by ThomasDaheim** [libasys/calendarplus#144]
Hi,

when trying to add a shared calendar via link in the web frontent I see "Import failed" and in the log I can find 2 entries like

<code>
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"#0 \/volume1\/web\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\DAV\Auth\Backend\AbstractBasic->authenticate(Object(Sabre\DAV\Server), 'ownCloud')\n#1 \/volume1\/web\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\Connector\Sabre\Auth->auth(Object(Sabre\DAV\Server), 'ownCloud')\n#2 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\Connector\Sabre\Auth->authenticate(Object(Sabre\DAV\Server), 'ownCloud')\n#3 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 \/volume1\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#6 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#7 \/volume1\/web\/owncloud\/apps\/calendarplus\/appinfo\/remote.php(84): Sabre\DAV\Server->exec()\n#8 \/volume1\/web\/owncloud\/remote.php(132): require_once('\/volume1\/web\/ow...')\n#9 {main}","File":"\/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}
</code>

immediately followed by

<code>
Undefined variable: count at /volume1/web/owncloud/apps/calendarplus/controller/calendarcontroller.php#521
Undefined variable: calendarid at /volume1/web/owncloud/apps/calendarplus/controller/calendarcontroller.php#521 
</code>

Looks like the http 401 happens e.g. with calendar as well (https://github.com/owncloud/calendar/issues/844) - might be a general problem. But still I would like to check here if anyone has any ideas on how to resolve?

Thanks,
Thomas

**Comment by libasys** [comment]
yes that is logical, you would like to share the complete webgui of the calendar, but it works if you go to the shared calendar and do a right click on the "Abonnieren" button and copy link to your calendars for subscribing!

url of the copied shared calendar looks like:

```
{yourdomain/owncloudinstance}index.php/apps/calendarplus/exporteventscalendar?t=uzj1R2CuctQwP8E
```

**Comment by ThomasDaheim** [comment]
OK, I now have
1. Copy the link when right clicking on the "↓" icon in my calendar (<code>{yourdomain/owncloudinstance}/index.php/apps/calendarplus/exporteventscalendar?calid=3</code>)
2. Added new calendar for another user and pasted URL into "Linked to subscribed calendar"

Results =
- Readonly subscription of my calendar
- No tasks are visible for other user
- "refresh subscribed calendar" takes forever and error <code>Error     PHP     Call to a member function getComponents() on a non-object at /volume1/web/owncloud/apps/calendarplus/lib/import.php#134 </code> shows up in the log

So I'm surely doing something wrong here since that is far away from definition of a "shared calendar"... Unfortunately, I haven't found any guide on how to setup a shared calendar and on how to use it (incl. tasks, read-write) as another user.

**Comment by ThomasDaheim** [comment]
Have learned something new: I don't have the "Share" icon on my calendar! Works for another ownlcoud user and now I have created the calendar there and shared with me - now also tasks work.
Any Idea how I cannot have the "Share" icon in the calendar (works, e.g. in Files)?

**Comment by Bullnados** [comment]
Perhaps Adblocker enabled?

**Comment by ThomasDaheim** [comment]
OMG - I would have never guessed that... Indeed, after disabling Adblocker for the domain the "Share" icon shows up.

That tip should be written in large + bold somewhere! Thanks a lot!
