### ISSUE TITLE
calender only visible for admin but nobody else

### ISSUE THREAD

**Issue by agreif** [libasys/calendarplus#145]
I am running Owncloud 8.1.1 (stable) and I Installed calenderplus 1.0.8.
as the initial admin I can see the calendar and use al functions.
But as any other user (does not matter whether in admin group or not) sees only the dark blue title bar, but beside this only a white page.

In the logs  I cammot se anything else.
 I am running on openbsd 5.8 in chroot with postgres.

Any ideas why inly the admin can see everything ans anyone else only a blank page?

Alex.

**Comment by libasys** [comment]
is there a js error in the browser log?

**Comment by agreif** [comment]
it is really strange.
the problem occured with the following install order: 1. contactsplus 2, calenderplus.
NOw I uninstalled all, and installed in the opposite order, and not it works fine.

But maybe a clean uninstall of bothe and then the reinstall helped. I dont know.

BTW there are no errors in the browser javascript console.

I Think the issue can be closed.

sorry for the noise,
ALex.

**Comment by agreif** [comment]
NOw I have the problem again...
here ist the console log:

right after the login:
GET https://myserver/index.php/apps/calendarplus/calendarsettingsgetusersettingscalendar
500 Internal Server Error

TypeError: CalendarPlus.calendarConfig is null
in app.js lines 1255 and 1179
...alendarConfig['defaultView'] === 'year' || CalendarPlus.calendarConfig['defaultV...
... if(CalendarPlus.calendarConfig['defaultView'] !== 'list'){...

it happens only on some users, not all

Alex.
