### ISSUE TITLE
Disscrambled View

### ISSUE THREAD

**Issue by hitam4450** [libasys/calendarplus#148]
I use OC 8.1.2 including Calendar+ 1.0.8, Activity 2.0.2 and Document 0.10.2 and direct menu 0.3

Whenever I select the calendar app I receive the following scrambled view:
![oc812d](https://cloud.githubusercontent.com/assets/9738727/9639288/a806f658-51ab-11e5-9442-00290a970071.png)

Selecting activity I receive this view:

![oc812e](https://cloud.githubusercontent.com/assets/9738727/9639191/225b5d64-51ab-11e5-9e97-7186d9ebb5fb.png)

Selecting Document i receive this view:

![oc812f](https://cloud.githubusercontent.com/assets/9738727/9639206/3418baf6-51ab-11e5-970d-eac3181ffc09.png)

Why is only the first view scrambled ?

regads, hitam4450

**Comment by libasys** [comment]
Please read other issues first, look for direct menu problem! thanks

**Comment by hitam4450** [comment]
Looking where???? Reference ???

That is the only incident, I had a scrambled view ! Only with Calendar+!

**Comment by libasys** [comment]
https://github.com/libasys/calendarplus/issues/124
