### ISSUE TITLE
bug in birthdays

### ISSUE THREAD

**Issue by ghost** [libasys/calendarplus#150]
i think, i found a bug in the birthday-calendar: i've got one contact in contact+ with the birtday 14. Sep 2012, but the calendar+ shows for this month "Name (2)" - so one year is missing. other birthdays/contacts seem to be right ...

**Comment by Bullnados** [comment]
Why missing a year? At the moment the person is 2years and 11 months.-->2years
At 14.Sept person gets 3years.
One day before 25th birthday you tell everybody you are 24.
Or do i missundertood something?

**Comment by ghost** [comment]
yeah, you're right, my bet.
i thought, it shows the birthday, but indeed it shows the age of the contact at the time you look at the calendar.
to be honest, i would prefer seeing the birthday instead of the age, but a bug it is not ...

**Comment by deMattin** [comment]
Hmm - now I also understand it and it is really weird and I would name it a bug.
No other birthday calendar behaves like that!
You expect seeing the x. birthday on the birthday date and not the today age if you look at a birthday event in the future like it is now!
So I agree with @lebkayn, that this should be changed or fixed.

With this birthday calendar, there seem some other enhancements possible and needed:
- display age on birthday event and not actual age on date of viewing (as mentioned above)
- also show birthdays in next and past years and not only in calendar of actual year!
- set color of birthday calender in GUI and not only in CSS (theme)

**Comment by libasys** [comment]
https://github.com/libasys/calendarplus/issues/1
