### ISSUE TITLE
Suggestion: replace "share calendar" link with "hide/show calendar" link

### ISSUE THREAD

**Issue by Visual-Notes** [libasys/calendarplus#156]
I think, it's an often needed feature to hide and show calendars, which is currently a bit hidden in the menu, while the switch to share a calendar is prominently positioned, but actually rarely getting changed.

That's why i think it would make sense to change the place of these two. Place a checkbox to hide/show a calendar left from the settings icon instead of the share icon/link, and move the share icon/link into the settings menu, where currently the hide/show icon/link is located.

The same would be true for Contacts+ by the way.
##

**Comment by farson2003** [comment]
@africanforest 
Agreed. Better usability would mean to have the hide/show button easily accessible, as it is needed more often.

**Comment by pravussum** [comment]
:+1:

**Comment by farson2003** [comment]
Why wontfix?

**Comment by Visual-Notes** [comment]
I presume it's because libasys wants to keep consistency in Calendar+, Contacts+ and Tasks+.
This button would have to be changed in all three apps. But why not, actually? Personally i'm not a big fan of this share mania and i doubt that calendars, address books and task categories are getting shared and unshared all the time in real life, so that there would be a great need for a button for that function on most prominent place. 
Another suggestion (which most likely won't get accepted either) is to use the existing checkbox for the "default" setting to show/hide calendars, adress books and task categories (if all are checked, all are shown, otherwise only the checked ones are shown). Also in this case, a function that is not often used (the "default" setting) is represented by a form element on most prominent place, while it could be easily placed in the settings menues (actually, the default setting is even more rarely used than the share function!).

**Comment by deMattin** [comment]
I also would appreciate the change.
Hiding (and showing again) calendars is a very often usecase especially in month view if you plan events.
In old official app it has been simply a click on the color but this is used here in calendar+ for default calendar switch.
Sharing is normally a setup function for calendars -  it's another workflow and usecase as for pictures and documents!

So @libasys please don't hide calendar on/off switch in settings menu.

**Comment by Berni-MD** [comment]
I am also of the opinion that could be optimized here. It is conceivable, for example, Also, by exchanging the buttons default calendar and the hidden buttons for hidden/show.
