### ISSUE TITLE
Vertical Scrolling Event-Title/Location

### ISSUE THREAD

**Issue by sahne123** [libasys/calendarplus#16]
![2015-07-10 17_12_29-kalender - owncloud](https://cloud.githubusercontent.com/assets/1149152/8621752/95a84e66-2727-11e5-9bdc-0261d9f90043.png)

I think we should override the `white-space: nowrap;` from here https://github.com/owncloud/core/blob/master/core/css/styles.css#L9 and add some padding for the icons on the right.

**Comment by libasys** [comment]
Latest commit calendar+ version 1.0.2 included!
