### ISSUE TITLE
Request: Search results closeable by mouse

### ISSUE THREAD

**Issue by pravussum** [libasys/calendarplus#161]
The search result sidebar can only be closed via keyboard (ESC), there should be another possibility to close it with the mouse for usability reasons. It took me a while to figure out, how to get rid of it.

E.g. a close button, or a click on the calendar hides it, ... Maybe it can be closed, when a result was chosen, etc...

**Comment by libasys** [comment]
fixed in current version

**Comment by pravussum** [comment]
:+1: Confirmed working. Thanks a lot!
