### ISSUE TITLE
Calendar Subscriptions are not updated automatically

### ISSUE THREAD

**Issue by matzex** [libasys/calendarplus#162]
As described in #61 subscribed Calendars are not updated automatically. With this behaviour the feature is useless for all people which are using Caldav to access the Calendar with other apps. I would prefer an automatic update. 
If this is not possible in the short future, is there a workaround for this? Is it possible to trigger an automatic update with a cronjob or something like this?

**Comment by libasys** [comment]
You can Commit a pull request, if you think this function is useless without automatic interval! Or you can add a bounty via bountysource!

**Comment by libasys** [comment]
added 5min sync refresh for subscription! added in current version!
