### ISSUE TITLE
Remote Calendars by cronjob

### ISSUE THREAD

**Issue by christianWilling** [libasys/calendarplus#173]
Is it possible to sync the remote calendars with the cronjob from owncloud?

I think this can be very useful when you just uses caldav and don't wont to open de web view every day

**Comment by matzex** [comment]
From my understanding, this problem should be fixed in the current version with https://github.com/libasys/calendarplus/issues/162#issuecomment-139922091.

**Comment by tschunk** [comment]
I don't think so. The commit behind #162 (5e1ff55) just refreshes remote subscriptions every 5 minutes if the calendar page is opened in the browser. As far as I can tell, it does not add support for updating calendars regularly via owncloud's cronjob.
