### ISSUE TITLE
Birthday calendar keeps subscribing

### ISSUE THREAD

**Issue by zion2k** [libasys/calendarplus#190]
It seems that everytime I login a new subscription of the birthday calendar is added.

ownCloud  8.1.1 (stable)
Calendar Plus  1.1.1
Contacts Plus  1.0.9

Any idea if I messed up the config or is it a bug?

**Comment by abyssox** [comment]
I already created an issue for that: https://github.com/libasys/calendarplus/issues/153
Workaround: https://github.com/libasys/calendarplus/issues/153#issuecomment-141783138

**Comment by zion2k** [comment]
Thank you for the note. I will close this issue and follow yours.
