### ISSUE TITLE
multiple entries for shared calendars with OC 8.2

### ISSUE THREAD

**Issue by kevinkk525** [libasys/calendarplus#192]
I upgraded OC from 8.1.3 to 8.2 recently and found a quite frustrating bug in calendar synchronization:
sharing calendars does not work in OC 8.2 with Calendar+ 1.1.1 anyways but because of the upgrade I already have shared calendars. If I insert a new calendar entry into a calendar that is shared with me (android client, worked perfectly before) , then the entry is shown as it normally would. but as the client synchronizes again, the entry is being added again. And there is no limitation to that resulting in events that i have 20 times in my calendar... This behavior only exists for calendars shared with me by other users, not with my own calendars.
##

**Comment by Berni-MD** [comment]
With shared calendars I fund also this bug: https://github.com/libasys/calendarplus/issues/186

But so far there ist no reaction on :-(

**Comment by Rotzbua** [comment]
It seems that "setCheckModifiedDate" does not work properly. So the bug is somewhere in `lib\import.php`, added by 5e1ff5541679431b7d3d7518bfb6682a6a22b6cc.
My temp fix: #195

**Comment by Rotzbua** [comment]
Also the birthday calendar duplicates, seems that every bithday gets a different uid while they are already listed.

**Comment by kevinkk525** [comment]
yeah that bug is also annoying and occurs also in OC 8.1.3., i had over 20 of those before i removed all of them...
The multiple entry occurs only in OC 8.2...
Thanks for the temporary fix, will try that it week.

**Comment by mmattel** [comment]
My birthday duplicates also even I have no birthdays set.
As I sync with the calendar with my IOS devices, this gets pretty annoying...
