### ISSUE TITLE
When creating event, it is not obvious in which calendar it is created.

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#21]
In contrast to the "native" calendar app, when workin with multiple calendars, is is not immediately obvious in which calendar a new event is   created.

A "drop down" where it can be selected (similar to the native app) would make it easier to understand for users.

**Comment by abyssox** [comment]
There is already a dropdown when you click on the color beside the title field. But you're right, it's not immediately obvious.
![2015-07-12 08_54_23](https://cloud.githubusercontent.com/assets/4539953/8636788/0f469a00-2874-11e5-9176-ce1bce9e8fb5.png)

**Comment by farson2003** [comment]
There is still a usability error. See screenshot. Depending on which calendar is selected, no field is obviously visible. I guess the reason is that the white calendar colour coincides with the white background (it is still selectable).

I would therefore suggest that calendar names are equally visible and not only their colour. This should also help users with many calendars with similar colors, where it is important to see the names to avoid confusion.

Please consider
![missing calendar selection](https://cloud.githubusercontent.com/assets/3358665/8637358/68dfd732-2885-11e5-8c85-72e3ac56a2d9.png)

**Comment by javaboyuk** [comment]
yes I agree with farson2003, I only found that out after googling etc, I would go with the name.

**Comment by sahne123** [comment]
@libasys I'm working on a solution for this. Almost done.

![2015-07-13 16_39_46-kalender - owncloud](https://cloud.githubusercontent.com/assets/1149152/8652314/5079184e-297e-11e5-8105-2f720b1c81e8.png)
![2015-07-13 16_39_15-kalender - owncloud](https://cloud.githubusercontent.com/assets/1149152/8652316/51e51e80-297e-11e5-97f8-1ddba5f52287.png)

@javaboyuk @farson2003 Do you think this solves the problem or do we need additionally a caption?

**Comment by libasys** [comment]
this should be tested and than become part of calendar+ version 1.0.3

**Comment by farson2003** [comment]
@javaboyuk @sahne123 @libasys 
As far as the images show it should be fine... Thank you!

**Comment by abyssox** [comment]
@sahne123 
This is how it looks like when i use your version.
![2015_07_31-09_11_50](https://cloud.githubusercontent.com/assets/4539953/9002442/856301ca-3764-11e5-9060-9059322fdb90.png)

EDIT: 
figured it out why: 

``` php
'asset-pipeline.enabled' => true,
```

in config.php was the cause. turned if off and now it's working.
