### ISSUE TITLE
Creating event shows up outside of screen.

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#22]
Using Firefox browser.
If an event is created, in some circumstances the creation mask appears outside of screen. This makes handling difficult  for users and should be improved

![event creation bad handling](https://cloud.githubusercontent.com/assets/3358665/8637362/b5388778-2885-11e5-8e8a-14e9034bc8d4.png)

**Comment by libasys** [comment]
Placement for popover now 'auto' detection
Latest commit calendar+ version 1.0.2 included!
