### ISSUE TITLE
Too many open windows (event editor and settings) make view unusable

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#23]
Steps to reproduce:
1. Click into calendar to create event and leave the edit form untouched.
2. Immediately click on calendar settings.

Both windows (settings and event editor) are open and one can not work properly.

![too many windows](https://cloud.githubusercontent.com/assets/3358665/8637426/50637fc0-2889-11e5-85d4-6878329c65f7.png)

(NB: It also appears that clicking on the cancel button in the event editor has no effect anymore...)

How it should be:
Suggestion: Show a warning and do not allow opening settings unless the event editor is closed

**Comment by libasys** [comment]
Fixed!
Latest commit calendar+ version 1.0.2 included!
