### ISSUE TITLE
Tickboxes in calendar selction panel unclear to users

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#24]
In the left calendar selection panel it remains unclear to users what the effect of the tickboxes are.

It would be adviseable to at least have a "mouse hover over" popup about them, I guess the left row selects the calendars which will be "actively shown" while the right row does what exactly?

See screenshot:
![unclear calendar selection panel](https://cloud.githubusercontent.com/assets/3358665/8637379/178e5c44-2887-11e5-8551-76c39d34042c.png)

**Comment by libasys** [comment]
Added Tooltips!
Latest commit calendar+ version 1.0.2 included!
