### ISSUE TITLE
Shared calendar only visible after deactivate and activate

### ISSUE THREAD

**Issue by abyssox** [libasys/calendarplus#26]
I have a shared calendar (delete,create,update,readonly). Everything worked fine but since today morning i can't see appointments from this calendar anylonger. I have to disable and enable the shared calendar, then all appointments are visible. After reloading the site all appointments are gone and again, i have to disable and enable the calendar.

**Comment by libasys** [comment]
update comes tonight!

**Comment by abyssox** [comment]
@sahne123
thanks for the quickfix

@libasys 
and the quick update :D

**Comment by libasys** [comment]
Latest commit calendar+ version 1.0.2 included!
