### ISSUE TITLE
can't create event with title>38 characters

### ISSUE THREAD

**Issue by UnnamedHero** [libasys/calendarplus#27]
steps to reproduce: 
1. create an event with title lenght > 38 characters. For example "это тестовое задание которое не сохр" - will work, "это тестовое задание которое не сохра" - will fail.
2. after pressing [OK] nothing happens.
3. Log message "Error   PHP Call to undefined function Sabre\VObject\mb_strcut() at [...]/3rdparty/sabre/vobject/lib/Property.php#247" ([...] - my path)
OS: CentOS 7.1.1507 [php php-5.4.16-36, postgreSQL postgresql-9.2.10-2]
OC: 8.1

**Comment by sahne123** [comment]
works for me using mysql. Maybe an postgresql issue?

**Comment by libasys** [comment]
yepp problem of the column definition in the database

**Comment by UnnamedHero** [comment]
Exists in 1.0.2.
