### ISSUE TITLE
expiration date of recurring events 

### ISSUE THREAD

**Issue by sahne123** [libasys/calendarplus#30]
If there is an expiration date of recurring events set, it's not displayed correct.

![2015-07-13 13_21_57-kalender - owncloud](https://cloud.githubusercontent.com/assets/1149152/8648642/949d50ec-2962-11e5-8906-ca4eb9e67227.png)

![2015-07-13 13_22_17-kalender - owncloud](https://cloud.githubusercontent.com/assets/1149152/8648637/87a8c5c4-2962-11e5-8cbb-99d4af1c4b62.png)

**Comment by libasys** [comment]
Latest commit calendar+ version 1.0.2 included!
