### ISSUE TITLE
Possibility to share a calendar to an owncloud group

### ISSUE THREAD

**Issue by Bullnados** [libasys/calendarplus#34]
Perhaps it is a stupid question, but is it possible to share a calendar to an owncloud group? In calendar settings i only see caldav-link

**Comment by libasys** [comment]
on the share dialog you can choose a user or a group! If group selected than the shared calendar shows on every users calendars!

**Comment by Bullnados** [comment]
Ok now i see the icon. Strange i#m sure that wasnt shown until i wrote my post here -.- 
Sorcery ^^
