### ISSUE TITLE
Option controls not visible

### ISSUE THREAD

**Issue by beccon4** [libasys/calendarplus#35]
It is not possible to change the settings or obtain the calldav url since the respective controls are not visible. (as seen in image 3 on the app.owncloud.org page) The gear, line and paper clip appear for a fraction of a second on their place at the right upper side - and then disappear. Nothing can bring them back.

I have jsxc installed which has a drawer at the right hand side which folds back when not in use. Perhaps the cause for malfunction of calenderplus controls?

**Comment by libasys** [comment]
it could be possible, if you have problems with the settings dialog on the  demo http://demo81.libasyscloud.de ?

**Comment by beccon4** [comment]
I disabled the ojsxc app and the controls appear. What happens is that this chat app reserves some pixels of space at the right hand side to implement a drawer for the roster. Obviously that mixes up the rendering. Hope this helps.

**Comment by efelon** [comment]
Observed the same behavior with my installation. (Calendar+ and ojsxc)

**Comment by libasys** [comment]
what is ojsxc?

**Comment by efelon** [comment]
It is a JavaScript XMPP Chat for owncloud which takes to complete right side to display the contacts.

https://apps.owncloud.com/content/show.php/JavaScript+XMPP+Chat?content=162257

**Comment by beccon4** [comment]
The ojsxc has a movable drawer at the right hand side which is perhaps the cause. It folds back when not in use - making the screen a bit narrower (only a couple of pixels) - to have a handle for the mouse to unfold it. When open it shows the roster (list of contacts) - maybe for that reason the width of the page is somehow odd.

**Comment by kevinkk525** [comment]
Same problem with my installation. While it loads the calendar the button is visible and if you click on it you can open the settings but of course not close again as the button disappears once everything is loaded. would be awesome if that could get fixed.
And i just realized, the ojsxc drawer is already loaded before calendar apps loads itself and in that process of loading the buttons disappear. the ojsxc drawer is there all the time.

**Comment by efelon** [comment]
The new update of ojsxc 2.1.0 seams to fix the issue. Controls are back and.
