### ISSUE TITLE
Calendar+ shows user less at one glance/needs more space than native app: Suggestions

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#36]
Comparing the original native calendar app with calendar+, it appears that all views show less of a timespan compared with the native app. 
I am sure @libasys decided so on purpose, to see more details. (Native app shows double the amount of time at one glance than calendar+).

Suggestion A:
It would be good if the user could select the amount of "rows" one hour consists of. (Similarly for the daily view and so on...). That way one could weigh "detailed view" against "better overview".

Also it appears that the actual calendar in calendar+ starts lower on the screen, because of the buttons above it. This results in less rows/space for the actual  calendar.

Suggestion B:
This might become technically difficult, as it might interfere with the OC core, but these buttons could be rearranged: Moved upwards (see screenshot), or other buttons where there is free space donwards/sideways. That way the actual calendar would gain 2-3 rows of space.

![calendar](https://cloud.githubusercontent.com/assets/3358665/8660942/1d2b71de-29ac-11e5-9a51-b9f21ec05cff.png)

![native caendar](https://cloud.githubusercontent.com/assets/3358665/8660861/749d00f0-29ab-11e5-8978-c92d1b39ff7d.png)

**Comment by BADF00D** [comment]
Maybe you can add a "Compact-View" Checkbox that compresses one day into the full height that is currently available.

**Comment by jancborchardt** [comment]
We should not make everything a setting but rather be reasonable and decide properly. The current calendar app uses a very similar space of time as other popular calendar apps.

Splitting the hour into quarters, reserving a row for each 15 minutes and as a result only making 5 hours visible at a time is really unnecessary and results in a Calendar app where you have no overview.

**Comment by jancborchardt** [comment]
@farson2003 and yep, I agree with you. While we don’ŧ want to cramp things, a lot of space here is simply filled up with unnecessary things, duplicated content or not used (such as the unfilled space to the bottom and the right of the week/month view).

**Comment by farson2003** [comment]
Wow! Just looking at 1.0.4 and this looks so much nicer (in my opinion!).
THank you!

**Comment by jancborchardt** [comment]
I totally agree with @farson2003. Giant improvements here and everywhere. Props! Let’s move forward together even better then :)
