### ISSUE TITLE
Other icon for menu (Calender+ and Tasks+)

### ISSUE THREAD

**Issue by Bullnados** [libasys/calendarplus#37]
would it be possible to change icon. So it will be easier to distinguish from other task and calendar app.
For exapmle a little plus in it.
Or isn't that changeable?

**Comment by libasys** [comment]
if you would like to make some svg and png icon for calendar+ and tasks+, you are welcome!

**Comment by Bullnados** [comment]
Ok i try my best perhaps today. But i cant promisse, that i get ready cause i'm within the exams.

**Comment by Bullnados** [comment]
It isn't perfect but i think its ok
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/8675241/087fbbd6-2a43-11e5-88f8-073fc6d98ce1.PNG)

**Comment by libasys** [comment]
We need only the icon not the description => format svg & png!
