### ISSUE TITLE
Creating new event gives 500 Internal Server Error (Chrome, IE11)

### ISSUE THREAD

**Issue by lookatmycode** [libasys/calendarplus#39]
When I click "OK" popover don't disappear and new event is not displayed on calendar until I refresh entire page. On debugger  I can see 500 Internal Server Error every time I press "OK". On Firefox everything works fine.

CalendarPlus: 1.0.2
OC: 8.1.0.8

**Comment by libasys** [comment]
Thanks for the bug report, can you add some information about your enviroment webserver, database, browser (mac, windows, linux). Are the problems exist on the demo http://demo81.libasyscloud.de, too?

**Comment by lookatmycode** [comment]
Yes, same thing on demo too.
OS Client: WIndows 8.1
Chrome version:43.0.2357.134 m
IE version: 11.0.9600
Firefox version: 38.0.5 (working as it should)
My server:
OS: Ubuntu 14.04.2 LTS
DB: MySQL  5.5.43-0ubuntu0.14.04.1
OC: 8.1.0.8
CalendarPlus: 1.0.2

**Comment by libasys** [comment]
Can you retest the demo please, and press F5 to load the page new, so that you don't have cache paradigmas! I added some clear function to the popover (it is a 3rdparty lib) and removed the nicescroll feature!

**Comment by lookatmycode** [comment]
Still the same 
https://gist.github.com/lookatmycode/307c2685d37a39d55304

![2015-07-15 13_05_55-kalender - libasys - more than a byte](https://cloud.githubusercontent.com/assets/13341221/8697179/4cede116-2af3-11e5-920c-7d9a52aca480.png)

![2015-07-15 13_06_05-kalender - libasys - more than a byte](https://cloud.githubusercontent.com/assets/13341221/8697191/59be20a4-2af3-11e5-9665-3b755646c41e.png)

![2015-07-15 13_06_26-kalender - libasys - more than a byte](https://cloud.githubusercontent.com/assets/13341221/8697194/64a6c91c-2af3-11e5-850c-939961b5062e.png)

**Comment by libasys** [comment]
Hi is there a log on your OC install in the admin settings like:

```
DateTime::__construct(): Failed to parse time string (Mon Jul 13 2015 00:00:00 GMT+0200 (Środkowoeuropejski czas letni)) 
Exception: {"Exception":"Exception","Message":"DateTime::__construct(): Failed to parse time string (Mon Jul 13 2015 00:00:00 GMT+0200 (\u015arodkowoeuropejski czas letni)) at position 34
```

**Comment by lookatmycode** [comment]
It look like it have problem with time zone containing Polish characters but it complaining about open bracket

```
DateTime::__construct(): Failed to parse time string (Wed Jul 01 2015 00:00:00 GMT+0200 (Środkowoeuropejski czas letni)) at position 34 ((): Unexpected character at /var/www/owncloud/apps/calendarplus/controller/eventcontroller.php#695
```

And:

```
Exception: {"Exception":"Exception","Message":"DateTime::__construct(): Failed to parse time string (Wed Jul 01 2015 00:00:00 GMT+0200 (\u015arodkowoeuropejski czas letni)) at position 34 ((): Unexpected character","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/calendarplus\/controller\/eventcontroller.php(695): DateTime->__construct('Wed Jul 01 2015...')\n#1 [internal function]: OCA\\CalendarPlus\\Controller\\EventController->newEvent()\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\CalendarPlus\\Controller\\EventController), 'newEvent')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\CalendarPlus\\Controller\\EventController), 'newEvent')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('EventController', 'newEvent', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/calendarp...')\n#9 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/calendarplus\/controller\/eventcontroller.php","Line":695}
```

**Comment by libasys** [comment]
Can you retest the demo now, if it works! F5 to clear cache!

**Comment by lookatmycode** [comment]
Still same problem. Have you tried removing entire bracket ? Maybe it will help

**Comment by libasys** [comment]
You have cleared your browser cache?

**Comment by libasys** [comment]
the problem is that the fullcalender.js transport your strange timezone with it?

```
Wed Jul 01 2015 00:00:00 GMT+0200 (Środkowoeuropejski czas letni)
```

and that is the problem

```
(Środkowoeuropejski czas letni)
```

**Comment by lookatmycode** [comment]
Yes, i even open it in dev mode with disabled caching.
Could you fix it somehow ?

**Comment by libasys** [comment]
if i look into the log of the demo i get now this error from your new event creation

```
DateTime::__construct(): Failed to parse time string (Wed Jul 01 2015 00:00:00 GMT-0700 (Pacific Daylight Time)) at position 41 (c): Double timezone specification at /is/htdocs/wp11048482_6MQ454GFGE/www/demo81/apps/calendarplus/controller/eventcontroller.php#695 
```

Do you running on a proxy for internet?

But this should fixed, if i test the date with the new function all works well! but i investigate!

**Comment by libasys** [comment]
if you watch on your inspector on my demo this line exists on app.js

```
validateEventForm : function(url,targetElem, calEvent) {
...
$('#viewstart').val($.fullCalendar.parseDate(viewObj.start));
```

**Comment by lookatmycode** [comment]
Yes, it exists.
"Do you running on a proxy for internet?" no i was tasting on VM with fresh chrome installation.

**Comment by libasys** [comment]
ok the problem is identified! i have to look for a server side solution! to get a working start and enddate!

**Comment by libasys** [comment]
please retest the demo now i test a server side solution!

**Comment by lookatmycode** [comment]
You are the best :P It's working
When will you commit the changes ?

**Comment by libasys** [comment]
Git version is updated to 1.0.3, please test so i can it upload to the appstore!

**Comment by lookatmycode** [comment]
I had tested it and now everything working good. Thank you for your patience
Edit:
I found one bug. If calendar is empty "Keine Termine vorhanden" is not translated to English.
