### ISSUE TITLE
caldav sync on iphone 5s (iOS 8.4) failed

### ISSUE THREAD

**Issue by ghost** [libasys/calendarplus#40]
Hi, i run your calendar+-App on my testenvironment ownCloud 8.1 but i am not able to use calendar+ on my iPhone. The setup completed successfully but no calendar is shown in the calendar app on the iPhone. On the web it works as expected and by the way: GREAT JOB!!!
Do you have any ideas what causes the issue on my iPhone?

**Comment by ghost** [comment]
I made a new/clean install of ownCloud 8.1 and now it works fine....

**Comment by libasys** [comment]
lol

**Comment by ghost** [comment]
i tried to implement hsts, memcache and many more...but i rather destroyed/crashed my environment than increase the performance and security. 
now, with a new fresh install, errors are gone...surprise surprise ;-)

**Comment by libasys** [comment]
;) :100:
