### ISSUE TITLE
Change color for Birthday calendar subscription

### ISSUE THREAD

**Issue by efelon** [libasys/calendarplus#41]
I'm playing around with your *+ apps because i like your design better than the one of the default apps. So far everything works fine. I now started playing with your contacts+ app and observed, that one can not change the color of the birthday subscription.

**Comment by libasys** [comment]
Hi, if you want to change the color of the birthday calendar, then you have to change this direct in the  source of contacts+.
The definition of the color is here:
https://github.com/libasys/contactsplus/blob/master/lib/hooks.php#L56

**Comment by efelon** [comment]
Thanks, it's working.
Just wanted to leave a feature request. ;)

**Comment by libasys** [comment]
;)

**Comment by libasys** [comment]
changed working process for calendar subscription, now the birthday calendar is a full caldav readonly calendar, so you can change color per Web Gui!
