### ISSUE TITLE
New calender upon reloading of the app

### ISSUE THREAD

**Issue by Styg82** [libasys/calendarplus#5]
I just installed calenderplus together with taskplus - great!
One serious bug that keeps me from using this productively is that I'm getting a new calender upon every reload of the calenderplus app. I'm also not able to delete them effectively ...

**Comment by libasys** [comment]
Hi @Styg82,
can you please give me some more information, about your enviroment what are you using, like apache,mysql etc! Which browser? If it possible a screenshot of that issue! Thanks for your bug report!

**Comment by Styg82** [comment]
![bugreportcalenderplus](https://cloud.githubusercontent.com/assets/11232625/8567269/40ec52f6-2564-11e5-9166-699ce420a0ce.jpg)

OC8.1 is running on an EC2 instance with Amazon Linux AMI release 2015.03
As it it's a test installation, I'm not using a (real) database right now.
Apache version is 2.4.12

**Comment by libasys** [comment]
If you not using a database, where is your data stored? Which Browser you are running?

**Comment by Styg82** [comment]
I'm using SQLite. Browser is chrome, but the behaviour stays the same with IE oder Firefox.

There are the following log messages in the admin backend:
Warning OCP\Share   Sharing backend \OCA\TasksPlus\Share\Backend\Vtodo not registered, \OCA\TasksPlus\Share\Backend\Vtodo is already registered for calpltodo   2015-07-08T09:11:48+00:00
Warning OCP\Share   Sharing backend \OCA\TasksPlus\Share\Backend\Vtodo not registered, \OCA\TasksPlus\Share\Backend\Vtodo is already registered for calpltodo   2015-07-08T09:11:43+00:00
Warning OCP\Share   Sharing backend \OCA\CalendarPlus\Share\Backend\Event not registered, \OCA\CalendarPlus\Share\Backend\Event is already registered for calplevent

**Comment by libasys** [comment]
The warnings normal comes on first init! Have you the same problems if you are using the "official" calendar app? How many entries are in the database table clndrplus_calendars? is there one or more entries for the duplicated calendars?

**Comment by Styg82** [comment]
The normal calender is operating normaly.
The table shows an entry for each calender, 19 at the moment.

![sqlitedump](https://cloud.githubusercontent.com/assets/11232625/8567869/f8990d50-2568-11e5-97c1-cd83ee4ffe65.png)

**Comment by libasys** [comment]
I have done a local test installation using sqlite as database, and used browser is chrome, firefox! i can't reproduce that issue! all works as expected! today i have updated the current master here for a postgresql bug, perhaps it works with the current master! If you would like to test, download the current master, rename the folder calendarplus-master to calendarplus, delete the old folder and upload it to your current app folder!

**Comment by Styg82** [comment]
Just used the new master, now I'm hanging in an "updating to 8.10"loop.
Reinstalled the old version, works again, but the bug stays the same.

**Comment by libasys** [comment]
if the updating loop exist, open your config/config.php and set maintance to false

**Comment by Styg82** [comment]
With the new master I'm hanging in a constant update-loop, maintenance is set to false.
Deletion of calendarplus leads to a white page, deleting tasksplus fixes this.
Had to remove both apps to get the cloud working normaly again. 
I guess I'll just wait for future releases. Thanks for your help!

**Comment by libasys** [comment]
I leave this issue open, perhaps some other users have the same problem as you! I am really sorry, but i can't reproduce that issue! The app is tested with mysql, postgresql, sqlite and all works fine!

**Comment by Styg82** [comment]
I just found out that "installed_version" stays at "1.0.0" in table oc_appconfig. Replaced it with "1.0.1", no more update-loop or white page.

Now with the new master, I'm staying with one calendar (which is quite nice). Thank you for your help again - now it's working. Really appreciate this great apps, as the original tasks app isn't too usefull for me.

**Comment by libasys** [comment]
thanks for the feedback! So i close that issue!
