### ISSUE TITLE
How can we help making your app "official" (not experimental anymore)

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#53]
Simple question as the title suggests.

**Comment by jancborchardt** [comment]
The guidelines on what to do to get »Approved« or even »Official« are in the documentation: https://doc.owncloud.org/server/8.2/developer_manual/app/publishing.html#official :)

**Comment by libasys** [comment]
_hust_ all criterias are fullfilled for approved btw official, more than the current "official" calendar app!

**Comment by jancborchardt** [comment]
The current Calendar app has been downgraded since some time already to be only »Approved«. :)

**Comment by farson2003** [comment]
If all criteria are fulfilled, why not make it "approved" or "official"?!

**Comment by jancborchardt** [comment]
The criteria are not yet fulfilled, most notably:

> - minimum of 2 active maintainers and contributions from others
> - security audited and design reviewed
> - follows app guidelines (especially the HTML/CSS guidelines)
