### ISSUE TITLE
Editing event resets field "To"

### ISSUE THREAD

**Issue by phsc84** [libasys/calendarplus#59]
Example:
You have an event on 25.07.2015, from 09:30 to 18:00.

Intention:
Now, you have to postpone the event to another day in the future.

Steps:
1) Open the event.
2) Edit the day in field "From".
3) The time in field "To" will now be set to 10:00.

Expected result:
The time in field "To" should still be set to 18:00.

**Comment by libasys** [comment]
that is the default beaviour of this function!

**Comment by deMattin** [comment]
And it's a usual function, I think.
Behavior should not be changed, to simply move events without adjusting Endtime.

**Comment by phsc84** [comment]
In my opinion, this is not a usual function. Try the same in Outlook or Thunderbird. Both behave different than Calendar+.

When you just switch the day of an event, you expect the time ("from" and "to") to remain the same.

**Comment by deMattin** [comment]
Sorry, haven't read your first post thoroughly enough.
But I checked it right now with 1.0.5 and am not able to confirm your scenario (1):
1. If I only change "from" date in a event with "from" time and "to" time on same day, the "from" and "to" time remain on there old values (like moving event to another day).
2. on events lasting  longer than 1 day, the "end"-date isn't changed as along, as end is later as start. If end would be before start, end will be set to start date or half an hour later than start time on start date. I have not been able to produce a not valid scenario.
3. If I edit an event and change only the "from" time, the duration of event remains. So, it's like a moving of the event to another time on the same day.
4. If you after changing of the date also change "from"-time, the "to"-time doesn't change (no moving of event). If you change so many values, I think, it isn't so bad to see it like a nearly new event where you are able to change any value independently.

**Comment by phsc84** [comment]
Ok, I will try with 1.0.5 later today or tomorrow.

**Comment by phsc84** [comment]
Can confirm, that the problem does not occur anymore in 1.0.7.
