### ISSUE TITLE
Replacing "standard calendar"

### ISSUE THREAD

**Issue by IzzySoft** [libasys/calendarplus#6]
It is not fully clear whether _calendarplus_ can be used to replace the "standard" calendar app, can co-exist with it, whether calendar events are "kept in sync" between the two (e.g. if an event created with one is automatically visible from the other), and if sync with the clients would simply "continue to work as if nothing had changed" when using _calendarplus_ instead of the "old calendar". The `README.md` seems to indicate some incompatibilities (quote: _old sharees won't work if you export the database shema from an old installation_).

Could you please point out a bit more detailed what has to be considered in this context – and what "migration steps" (if so) have to be performed? I'd really like to try your app, but I don't want to risk breaking my installation, having to re-configure all my clients (on several Android devices and Linux machines), or having to re-create existing shares (mine and those of other users on this installation). Thanks in advance!

---

PS: Just found [this related issue](https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/26) answering parts of my questions:
- _calendarplus_ works with seperate database table – so the two can definitely co-exist (though this doesn't answer whether they are kept in sync with each other, which under this circumstances I doubt)
- it supports CalDAV, but uses different URLs for sync. So this means all clients have to be re-configured. This obviously will pose problems especially for larger installations, especially as (according to the `README.md`) migration must be done via desktop export (?) – which makes an "easy transition" impossible on those (must wait until the last user has "migrated" before being able to drop/disable the "old calendar").
##

**Comment by libasys** [comment]
Hi @IzzySoft thanks for your response, i would try to explain why this steps was needed! (no native english speaker)
I have seperated the calendar+ completely from the current official calendar app, calendar+ uses seperate database table and seperated sharing backend names for the database and the remote address for caldav syncing has changed too! So calendar+ is a complete seperate calendar app!
You can just try it and install both on a testenviroment! There are no conflicts! So migration becomes easier (import/export) from one calendar app to the other! Why i have done this, cause i am wasn't really happy with the current calendar app and have had long discussions with core developers without any results! I prefer a settings dialog to setup and customize the calender, f.e. choosing active views! I prefer a right sidebar to show up tasks and so on! The calendar app was round a year unmaintained cause the maintainer of the app hasn't much time, so only bugfixes became integrated! A lot of good pull requests never got commited, like the public sharing feature! 

At the end the user now have the choice which calendar app, he would like to use! A rework from the official calendar app is in progress and will become released with OC8.2 or later! So it is your decision which one  would you like to choose and run!

**Comment by IzzySoft** [comment]
Don't get me wrong, @libasys – I totally like the interface of _calendarplus_ from what I've seen (or wouldn't have bothered to report here in the first place). My main concern was the lack of documentation for migration / parallel use, which IMHO require clarification. I'm aware of the fact that "documentation needed" already is an open task, but was hoping to have this confusion solved before.

> no native english speaker

Neither am I. But I'm pretty sure we share our native language – so feel free to drop blocks others have to GTrans then _LOL_

I understand the reasons behind it (and applaude them – the right choice if you ask me). It's good to have a chance to test it first independently without having to be afraid of breaking your "real calendar". The only drawback might be the migration then. Would be much preferable to have a "simple script" to be run at the shell- or database prompt doing this job for the entire calendar (once one has decided to switch). As for the CalDAV URLs, maybe someone can figure a rewrite rule for the web server (e.g. `mod_rewrite` with Apache), to ease transition and save us from the need of having to migrate "hundreds of clients at once" (existing configurations would be re-directed, for new ones the new URLs be used).

Of course, "Rome wasn't build in a day". From the release notes, I'm even confused whether upgrading OC to 8.1 would keep my clients in working order (does dropping that SabreDAV browser mean the URLs for WebDAV have changed, or clients are no longer able to find existing calendars/address-books themselves via that URL?) – so I decided to wait a few weeks with that and then first check the net for the "big shit-storm". Which means, currently I'm checking for "the route to take when the time comes".

Thanks for responding that fast! If you could write-up a summary for the "migration-guide" in German (Stichworte are OK), I'd gladly accept the task to "convert that to English" so you can integrate it with `README.md`. You can find me via my profile page, if you prefer to email.

---

For now, may I suggest some update to the `README.md` in "Setup Info"? In Markdown for you to copy and paste:

```
**This version of the calendar app is only compatible with ownCloud Version 8.1 or later!**

You can use *calendarplus* parallel to your current calendar application: it works on its own tables, so you can thoroughly test it without the risk of messing up your existing calendars. If you want to use your old calendar events, you have to export them using a desktop calendar application or the web interface, and import them to *calendarplus.* It won't work to simply export the database from an older installation of ownCloud.
```

**Comment by IzzySoft** [comment]
Closing this as the project is no longer maintained and I'm using the main calendar again.
