### ISSUE TITLE
Imported events are not editable via CalDAV

### ISSUE THREAD

**Issue by phsc84** [libasys/calendarplus#60]
Events, that were imported are read-only via CalDAV (e.g. Android Smartphone). The same events can be modified in Owncloud.

Newly created events can be modified via CalDAV. It does not matter, whether these newly created events were created in Owncloud or via CalDAV.

**Comment by libasys** [comment]
Hi @phsc thanks for your bug reporting! Imported events by subscription (external Link) or per ics file?

**Comment by phsc84** [comment]
The events were imported per .ics file.

**Comment by libasys** [comment]
Have the imported events organzier and attendees parts?

**Comment by phsc84** [comment]
No, they are very simple, e.g.:
- Title = "Visit xyz"
- Date from = "18-07-2015 11:00"
- Date to = "18-07-2015 17:00"

No other fields are set.

**Comment by libasys** [comment]
Have you an example ics file, so i can investigate further?

**Comment by phsc84** [comment]
Yes, I will upload one later today.

**Comment by phsc84** [comment]
@libasys Your hint with ORGANIZER was perfectly correct. Events with ORGANIZER are not editable via CalDAV, events without ORGANIZER are editable. I just thought, that the events did not contain the field ORGANIZER, because this field is not visible in Owncloud.

I followed the following workflow:
1) Create the events on Android.
2) Sync them to Owncloud 6 via CalDAV account "A".
3) Export the whole calendar as .ics file.
4) Import the whole calendar into Calendar+ (Owncloud 8.1).
5) Set up new CalDAV account in Android (e.g. "B").

The field ORGANIZER is filled with the name of the old CalDAV account in Android ("A"). If it helps, you can download an example .ics file, with which you can reproduce the problem, here:
http://netplate.net/download/test.ics

**Comment by libasys** [comment]
```
BEGIN:VEVENT
DTSTAMP:20150715T053443Z
UID:20150715T053443Z-3391@487e32e3d3edc396
DTSTART;VALUE=DATE-TIME:20150718T173000Z
DTEND;VALUE=DATE-TIME:20150718T193000Z
SUMMARY:termin2
STATUS:CONFIRMED
ORGANIZER:mailto:Philip-CalDAV
LAST-MODIFIED:20150715T053443Z
END:VEVENT
```

your organizer "Philip-CalDAV" is not valid or unknown so the event is become "readonly"! If you work with organizer you have to setup a email address on personal settings ownCloud before you enter the syncing link to your android phone! And on your android phone you should have also the same email setup to your mail program, then this should work!

**Comment by phsc84** [comment]
The strange thing is, that I never add the field ORGANIZER myself. It seems, that Android adds the name of the CalDAV account as ORGANIZER. And the CalDAV account name can be anything and is not necessarily an email address.

The following example is a newly created event in Android, which was synced via CalDAV and then exported with Calendar+. The field ORGANIZER is filled with the CalDAV account name, which is not a valid email address, but the event is editable in Android and in Calendar+.

``` BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 1.0.3
X-WR-CALNAME:Test
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:CEST
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:CET
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20150728T065732Z
UID:20150728T065732Z-7876@487e32e3d3edc396
DTSTART;TZID=Europe/Berlin:20150728T100000
DTEND;TZID=Europe/Berlin:20150728T110000
SUMMARY:Test
STATUS:CONFIRMED
ORGANIZER:mailto:phs@caldav
LAST-MODIFIED:20150728T065732Z
END:VEVENT
END:VCALENDAR
```

**Comment by libasys** [comment]
if you change your ORGANIZER to phs@caldav then all your old events are editable! The organizer part is really nasty, cause every calendar app doing different things with it!

**Comment by phsc84** [comment]
Ok, I understand. In this specific case, it is an Android problem. If the field ORGANIZER differs from the CalDAV account name, then the events are read-only.
Would it be possible to display the field ORGANIZER in Calendar+? This would help to identify such problems. Furthermore you could show a hint in the settings, which advises the user, that the name of the CalDAV account should correspond with the field ORGANIZER.
I think this could help many users, as Android is very widely spread and this problem could possibly affect some users.
