### ISSUE TITLE
Interval for updating web ressources over external link

### ISSUE THREAD

**Issue by godfuture** [libasys/calendarplus#61]
Hi folks,

I just have added a new holiday calendar and noticed that this works great! But then I noticed I cannot set the update interval for this external reference, only manually triggered update available.

Does it cost much effort adding a possibility to set the update interval?

**Comment by libasys** [comment]
Yes, at the moment this not added as automatic interval, here we have the refresh button to update  the subscribed calendar!

**Comment by matzex** [comment]
Are there any plans to change this behaviour?
For me the subscribe feature is useless if the calendar is not updated automatically.
