### ISSUE TITLE
Having problems to subscribe a calendar wich is protected by username and password

### ISSUE THREAD

**Issue by tschnied** [libasys/calendarplus#62]
Hi libasys,
first at all - thanks a lot for work with the calendarplus app!!
I have the following problem:
I would like to subscribe the following calendar:

http://kalender.mhsmannheim.de/Schulkalender.ics

The problem I have is, that the acces of this calender needs a usernamer and a password. I can`t figure out how to put in the username and the paswword in your calenderplus app.
Is there a way how I can subscribe this calendar?

Thank you very much for your help.

Best regards Thorsten

**Comment by libasys** [comment]
Test this: 

http://user:password@kalender.mhsmannheim.de/Schulkalender.ics

**Comment by tschnied** [comment]
Hallo Sebastian,

ich schreibe einfach mal auf gut Glück auf deutsch zurück :). Wenn ich Deinen Tipp versuche, importiert calenderplus eine ganze Weile lang (Bild 1) und hört nach ca. 3 Minuten ohne Fehlermeldung auf (Bild 2). Ich habe Owncloud heute frisch installiert (8.1) auf einem Ubuntu 15.04 System.
Wenn ich die private URL meines Googlekalenders importiere funktioniert der Import ohne Probleme.

Hast Du noch einen weiteren Tipp für mich?

Viele Grüße

Thorsten 

Bild 1:
![1](https://cloud.githubusercontent.com/assets/13568527/8980385/77a5dfda-36b0-11e5-93b2-e91fb91738b1.JPG)

Bild 2:
![2](https://cloud.githubusercontent.com/assets/13568527/8980388/7bfec52e-36b0-11e5-8571-af227777b31b.JPG)

**Comment by libasys** [comment]
Hallo @tschnied, kein Problem ich verstehe auch deutsch, ist nur für die anderen User die eventuell das gleiche Problem haben, aber nur englisch können! Bezüglich deines Versuches den Kalender zu importieren, kann das viele Möglichkeiten geben, wieso das nicht funktioniert. Was passiert wenn du die URL für den Kalender direkt in die Addressleiste deines Browsers eingibst, sprich mit Passwort und Username? Startet dann automatisch der Download oder kommt da was anderes? Das 2. Problem ist dass du das Passwort über http und nicht verschlüsselt über https sendest, so könnte man dein Passwort ohne Probleme auslesen!

**Comment by tschnied** [comment]
Hallo Sebastian,

danke für Deine schnelle Antwort! Wenn ich Deinen angegebenen Link direkt in den Browser eingebe kommt folgendes Fenster:
![3](https://cloud.githubusercontent.com/assets/13568527/8981148/5b2d948c-36b6-11e5-9712-7ffe02795d44.JPG)
Wenn ich dann mit ok bestätige wird die Datei heruntergeladen. Zu dem 2. Problem, kann ich nichts ändern, das wurde von unserem Admin an der Schule zu eingerichtet (bin Lehrer).

LG Thorsten

**Comment by libasys** [comment]
Deswegen funktioniert auch der Import mit der Zwischenabfrage nicht, deswegen den Kalender herunterladen und dann einfach per Drag & Drop importieren!

**Comment by tschnied** [comment]
Dank Dir für Deine schnelle Hilfe :). Wenn ich das aber z.B. mit thunderbird/ lightning versuche, klappt es ohne Probleme :( - hätte es gerne voll automatisch mit Owncloud gehabt - egal kann man wohl nichts machen - viele Grüße!!

Thorsten

**Comment by tschnied** [comment]
Habe gerade gemekrt, dass falls ich das gleiche mit chrome versuche, wird der download automatisch gestartet - leider klappt das nicht in der calenderplus app und chrome :(
