### ISSUE TITLE
[suggestion/enhancement] 12h display improvements

### ISSUE THREAD

**Issue by ERamseth** [libasys/calendarplus#64]
Currently, when in 12h display mode, the time of an event is displayed as follows:

18:00 = 06:00 pm

I suggest it should be displayed as 

18:00 = 6:00 pm

**Comment by libasys** [comment]
without leading zero?

**Comment by ERamseth** [comment]
Leading zero is not typical in my experience, and could be odd looking to some folks.

-------- Original Message --------
