### ISSUE TITLE
Can't create new event

### ISSUE THREAD

**Issue by marillat** [libasys/calendarplus#7]
Hi,

Maybe I'm stupid but I'm unable to create a new event.
I can select a time range but no popup box is opened when a release the left mouse button...

Server is Debian testing with 
owncloud 8.1 and browser is iceweasel 38.1.0 Also tested with firefox 39.0 under windows 8.1

**Comment by libasys** [comment]
Hi @marillat thanks for your bug report, i need some more info, what is your running enviroment like webserver, database etc! Have you a demo link where i can look for?

**Comment by ghost** [comment]
I got a similiar problem. I´m able to enter all the data, title, date etc. but after clicking on 'OK' the Popup doesn´t close itself.  I click again and again, but nothing happens. Then, after refreshing the Page, the event showed up, numerous times, because I clicked so many times. 

OC 8.1.0 with MySQL Database running on All-Inkl Webspace, Windows 7 64-bit, both Opera and Chrome, same behaviour.

**Comment by libasys** [comment]
Hi @edelrost here we had the same issue: https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/14
Could it possible you have some popup blockers on your browser, or something else?

**Comment by marillat** [comment]
The server is Debian testing
apache 2.4.10
mysql 5.5.43
php 5.6.9

But now I can create a new event with the test user I've created...

You can try here : user "test" pass "test"
http://www.marillat.fr/owncloud/index.php/apps/calendarplus/

Tested with iceweasel 38.1.0 Linux Debian unstable and  firefox 39.0 under windows 8.1

**Comment by libasys** [comment]
Hi @marillat, i can create new events without any problem! Tested with Firefox on Mac, but you get a js error from encryption

```
TypeError: OC.Encryption.displayEncryptionWarning is not a function
```

And so it could possible that IE11 crashes !

**Comment by marillat** [comment]
@libasys Yes I know this work only with this new user.
Otherwise I don't if it is important but I see that on my machine 

JavaScript error: http://www.marillat.fr/owncloud/apps/calendarplus/js/app.js?v=841a87496fd0f645dfcdb7638bbd64bc, line 1820: TypeError: CalendarPlus.calendarConfig.calendarcolors[calId] is undefined

**Comment by libasys** [comment]
Yes, it is important you have to add a calendar as choosencalendar by clicking on the color (left side) of the calendar, and a checkmark will be shown! And than the js error goes away!

**Comment by marillat** [comment]
I've already a calendar and this calendar is selected and the message error is still the same.

**Comment by libasys** [comment]
Have you clicked in the colored square field on the left of the calendar and you have a checkmark?
![calendar](https://cloud.githubusercontent.com/assets/2439975/8614489/5e1cdaee-26ea-11e5-867e-f9fd8ee043f0.jpg)

**Comment by marillat** [comment]
No, and now it works. I think the most left square field was enough.
Is the documentation available ?

Anyway many thanks for your work;

**Comment by libasys** [comment]
can you reopen please a test account for me on your cloud?

**Comment by marillat** [comment]
I don't know if you have seen my previous comment.

This "bug" is simply a problem with a lake of documentation.

**Comment by libasys** [comment]
Hi @marillat this should not happend cause by default on your first init, a choosen calender is select! Documentation is coming, but i am at the moment a one men show! Docu writer welcome!

**Comment by marillat** [comment]
Not documentation but I can do French translation.

**Comment by libasys** [comment]
you are welcome! thanks for your help :+1:
