### ISSUE TITLE
wrong arg type in deleteCalendar

### ISSUE THREAD

**Issue by Pawel-Panek** [libasys/calendarplus#72]
Fatal error thrown on https://github.com/libasys/calendarplus/blob/master/lib/calendar.php#L374
Example log:
"Call to a member function getUID() on a non-object at \/var\/www\/owncloud\/lib\/private\/group\/group.php#113". Ref.: https://github.com/owncloud/core/blob/master/lib/private/group/group.php#L107

Function inGroup expects OC\User object but string is passed.

It's causing 500 error on user delete action (via post_deleteUser hook).

**Comment by libasys** [comment]
Please give me some more information about your environment and some steps explained what you have done! Thanks!

**Comment by Pawel-Panek** [comment]
Hi,

Using ownCloud 8.1.0.

Steps to recreate:
1. Enable logging in conf.php (level 3 or above)
2. Login as ownCloud admin and add a user
3. Delete user
4. Check data/owncloud.log for errors

To fix this I had to replace mentioned line with:

if($calendar['userid'] != $user && !$group->inGroup(\OC::$server->getUserSession()->getUser())) {

$user is a type of string where inGroup method expects an object - it calls getUID on passed object.
