### ISSUE TITLE
Don’t duplicate calendar list in settings, and move »Add calendar« function in left sidebar

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#73]
@libasys as talked about at the ownCloud meetup, we shouldn’t have 2 calendar lists which are essentially the same. The list should only be in the left navigation sidebar.

Just now I installed the Calendar+ app again and was confused as to how to add a new calendar. It’s just not really discoverable when it’s in the settings.

**Comment by libasys** [comment]
If you have a look on the rework tree this is all moved to the left sidebar!

**Comment by jancborchardt** [comment]
@libasys great stuff! :) I just opened this because I wasn’t sure of the current state because it’s not visible anywhere. A work-in-progress pull request would be good. And as said, we should merge the rework stuff as soon as possible to not repeat the mistakes we made with Calendar. cc @DeepDiver1975

**Comment by jancborchardt** [comment]
WOW DUDE! @libasys I just got latest master and it looks sooo much more awesome! :) Still of course stuff to polish and fix, but man this is a **huge** step!

@owncloud/designers @georgehrke @DeepDiver1975 @LukasReschke please have a look at current calendarplus master. :)
