### ISSUE TITLE
»Extern Link« field when adding a new calendar

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#74]
When adding a new calendar, there is a strange field called »Extern Link«. What does this do? It seems very confusing at the step of simply adding a calendar.

Adding a calendar should be just one line. On the left the color picker square, then the input field with »Calendar name« as placeholder, on the right a button with `.icon-confirm` as class to show the correct icon. Makes it much simpler – similar as for the Bookmarks app https://github.com/owncloud/bookmarks/pull/170

**Comment by libasys** [comment]
External Link is for subscribing to calendars, and so this is a part of add a new calendar, we can change the placeholder text to "External link to subscribed calendar"

**Comment by jancborchardt** [comment]
Aaah ok! Then it should be two different sections:
- Calendars (the normal calendar list, doesn’t need a header), with a »New calendar« function on the bottom of the list
- Subscriptions, with a »Subscribe to calendar« button (or similar) on the bottom of the list

In the current flow it’s quite confusing as you don’t really know that it’s a choice of either calendar name or external link.
