### ISSUE TITLE
Non-standard loading spinner

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#75]
The loading spinner is quite big and looks unlike the normal spinner used everywhere else in ownCloud. This is quite confusing and puts too much emphasis on the loading process. (Makes the app appear slow in the end.)

Instead, simply use the class `.icon-loading` to invoke the standard loading spinner.

**Comment by libasys** [comment]
could be possible to add the default loading spinner in a later version of calendar+ app!

**Comment by jancborchardt** [comment]
Ok. Would be good to do that for 8.2 for sure. You already have the loading spinner here at https://github.com/libasys/calendarplus/blob/master/img/loading.gif – if you tell me where the other spinner is I will open a pull request to replace it. :)

**Comment by jancborchardt** [comment]
Thanks!
