### ISSUE TITLE
Show/hide calendar should not invoke full-screen loading

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#76]
There’s too many uses of the blocking full-screen loading spinner where it’s not necessary. One of them is showing/hiding a calendar in the left sidebar. This makes the interface seem quite slow and is annoying.

Instead, there should only be a small spinner, for example overlaying the checkbox you just clicked, or in place of it.

**Comment by libasys** [comment]
But what happens if a calendar is disabled, the eventsource get removed, so the whole calendar is affected. For my opinion it make sense to see the overall loading spinner!

**Comment by jancborchardt** [comment]
> the eventsource get removed, so the whole calendar is affected.

These are technical details which we should not reflect in the interface.

I expect the calendar entries to simply hide, not to have a full-on blocking loading screen. Other calendars don’t do this either because it’s quite intrusive.

**Comment by jancborchardt** [comment]
Great stuff!
