### ISSUE TITLE
Subscription to public google calendar fails

### ISSUE THREAD

**Issue by nblock** [libasys/calendarplus#8]
The subscription to a publicly available google calendar fails with the error message: "Import failed"

I tried it with this link:
https://www.google.com/calendar/ical/de.austrian%23holiday%40group.v.calendar.google.com/public/basic.ics

**Comment by libasys** [comment]
Thanks for your bug report! I tried it on the Demo https://ssl.webpack.de/demo81.libasyscloud.de and it works without problems!

**Comment by nblock** [comment]
Thanks for your quick reply! I guess my setup is somehow broken as on each request a new local calendar is created as well.

**Comment by libasys** [comment]
you are using sqlite as database? if yes have a look here: https://github.com/libasys/calendarplus/issues/5

**Comment by nblock** [comment]
You are right, I'm using sqlite and with the help in #5, the issue with the new calendar on each request is now gone. However, the import of google calendar ics links still fails. Other ics files such as http://valug.at/calendar/valug.ics work as expected.

The log has the following entries during import:

```
{"reqId":"clpthi8BJWIqyBp3v23h","remoteAddr":"::1","app":"PHP","message":"Undefined variable: count at \/var\/www\/html\/owncloud\/apps\/calendarplus\/controller\/calendarcontroller.php#482","level":3,"time":"2015-07-09T07:07:27+00:00"}
{"reqId":"clpthi8BJWIqyBp3v23h","remoteAddr":"::1","app":"PHP","message":"Undefined variable: calendarid at \/var\/www\/html\/owncloud\/apps\/calendarplus\/controller\/calendarcontroller.php#482","level":3,"time":"2015-07-09T07:07:27+00:00"}
```

**Comment by kennyMC** [comment]
i have a similar problem with this calendar:
http://cal.to/ical/65/bayern/feiertage/60a6e5bf.fd79db29-83df697b.ics

This from the errorlog:
Error   PHP Call to a member function getComponents() on a non-object at /var/www/clients/client1/web2/web/apps/calendarplus/lib/import.php#134

thx in advance
