### ISSUE TITLE
Event popover scrolling

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#81]
When you scroll, the event popover should move as well. Currently this happens:
![capture du 2015-08-11 21-13-20](https://cloud.githubusercontent.com/assets/925062/9207441/fc66c722-406d-11e5-8a8f-92bbf9a68172.png)

**Comment by libasys** [comment]
not possible at the moment! google calendar has the same behaviour on scrolling!

**Comment by jancborchardt** [comment]
@libasys then still keep the issue open though. ;D It’s something we should eventually fix, when we find out how.
