### ISSUE TITLE
Sliders for time selection are not acceptable

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#83]
This:
![capture du 2013-11-01 01-31-57](https://cloud.githubusercontent.com/assets/925062/9207495/4954d95c-406e-11e5-8687-fb3031e9ac9d.png)
is one of the strangest interfaces I have ever seen for time selection ever.

Here is some relevant art from well-known calendar apps:
![capture du 2015-08-11 21-19-49](https://cloud.githubusercontent.com/assets/925062/9207565/beedefc8-406e-11e5-871d-0e1ec09214d4.png)
Google Calendar uses a dropdown with half-hour sections. You can manually adjust in the input field.

![capture du 2015-08-11 21-19-13](https://cloud.githubusercontent.com/assets/925062/9207564/beecbd74-406e-11e5-978a-552d3e23b981.png)
In iCloud, you can only adjust via the input field. Since for both calendars the input fields are of input type="date", the appropriate interface will show on mobile.

**Comment by libasys** [comment]
Could be an enhancement, for some later version of the calendar! Thanks for the hint!

**Comment by jancborchardt** [comment]
Cool! :) I’d say putting in the time is pretty basic though, so we should prioritize this. Currently it’s not possible to put in time by simply clicking into the input field and changing it via keyboard.

**Comment by MNOCFan** [comment]
I would like to add that what would also be nice to see, although not a demand :), something like in the google calendars when you add an event and you start it with something like "7:45am Doctors Appointment" google will automatically add an event called "Doctors Appointment" and set it for 7:45am for that day. It makes entering events super fast and easy. Just an idea. :)

**Comment by jancborchardt** [comment]
@MNOCFan entirely different topic – open a separate issue please.

**Comment by MNOCFan** [comment]
@jancborchardt Understood.

**Comment by libasys** [comment]
added new timeslide like google, icloud => new master available version 1.0.5

**Comment by jancborchardt** [comment]
Yeeeha, thank you! :)
