### ISSUE TITLE
Technical calendar ID info in interface

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#84]
![capture du 2015-08-11 21-26-15](https://cloud.githubusercontent.com/assets/925062/9207735/a9309d74-406f-11e5-8b21-9b082dd78945.png)
The ID does not need to be exposed here. It’s technical information and has nothing to do in the interface.

**Comment by libasys** [comment]
The ID is needded for the additional share.config.js, to define an own public sharing calendar, showing up header etc!
https://github.com/libasys/calendarplus/blob/master/js/share.config.js

**Comment by jancborchardt** [comment]
That doesn’t mean it needs to show up all the time though, right? Could be a tooltip for example, or something which shows up in the editing view?
