### ISSUE TITLE
Move settings to bottom left

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#86]
The settings popover in the top right is an outdated pattern. ownCloud apps use the settings area in the bottom left, as defined in the documentation: https://doc.owncloud.org/server/8.0/developer_manual/app/css.html#settings-area

**Comment by farson2003** [comment]
That seems related: https://github.com/libasys/calendarplus/issues/36

**Comment by libasys** [comment]
on the rework tree the settings dialog is on the left bottom sidebar!

**Comment by jancborchardt** [comment]
Awesome! :) Pull request please so we can review. cc @DeepDiver1975
