### ISSUE TITLE
Get rid of header bar, allow calendar to take up more space

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#87]
As soon as these are solved:
- move calendar list to left sidebar: https://github.com/libasys/calendarplus/issues/73
- move tag editing list to left sidebar too: https://github.com/libasys/calendarplus/issues/85
- move settings to bottom left: https://github.com/libasys/calendarplus/issues/86

We can also move the Day/Week/Month switcher to the top of the left sidebar. Then we can get rid of the top bar, and the calendar can take more space. More room for content – the important thing here.

**Comment by farson2003** [comment]
That seems related: https://github.com/libasys/calendarplus/issues/36

**Comment by libasys** [comment]
Not possible at the moment cause you have settings button for show left siderbar and on the right the task bar so the day/week/month switcher keeps in the middle of the header

**Comment by jancborchardt** [comment]
We’ll get there. :) Similar to in the mobile interface, the items to show the left sidebar (and right one) should be in the content view, not in a header.

**Comment by libasys** [comment]
all done with current master!

**Comment by jancborchardt** [comment]
@libasys awesome! :) I hope that the other discussion thread doesn’t get you down – we all want to push forward a more awesome calendar app for ownCloud.
I hope with the rework stuff being in master (right) we can move forward and also get more contributors on board. :)
