### ISSUE TITLE
Missing Settings, Taskbar and Category button when XMPP plugin activated

### ISSUE THREAD

**Issue by muppeth** [libasys/calendarplus#89]
When activating xmpp plugin https://apps.owncloud.com/content/show.php/JavaScript+XMPP+Chat?content=162257 buttons on the top right disapear. I guess it has to do with xmpp taking up some space in there. Other buttons move to the right ("Day", "Week", "Month").

Besides that, it's a great app I've been waiting for for a long time. Keep up the awesomeness!

**Comment by muppeth** [comment]
changing in style.css width of .centerControls 10% smaller fixes the issue:
`
.centerControls{
        position:relative;
        float:left;
        width:58%;
        text-align:center;
        display:block;
`

**Comment by libasys** [comment]
with new version (1.0.4) on master this is fixed
