### ISSUE TITLE
Bad position of bubble & size of timetable

### ISSUE THREAD

**Issue by mitpro** [libasys/calendarplus#9]
When click on a event to get more information or edit the event, the bubble got a bad position:
At "big events" (when the end of the event is out of the windows) the bubble would create at the end of the site.

The tablesize is not optimal for using in the browser - scrolling is required.
Maybe an option to autosize the height or something else..?

**Comment by libasys** [comment]
yes it is an autosizing  and scroll problem! the content of an event get loaded per ajax and the content have than a variable height!
