### ISSUE TITLE
Calendar Color

### ISSUE THREAD

**Issue by marvin-martian** [libasys/calendarplus#90]
I find the Calendar Color widget not very user friendly as you cannot choose an exact color. Using the JS color palette is like throwing a dart.  It would be nice to be able to set a color by hex code, or to save same colors to a palette for reuse. I also notice that the color of a shared calendar cannot be changed by the person it is shared to. You would think the color of all calendars including shared calendars is the personal choice of every user. 

This also applies to the colors of the tags.

Anyway this is just a usability feature request.

**Comment by libasys** [comment]
added smaller color chooser, now with hexcode! in current master available!

**Comment by deMattin** [comment]
:+1:
