### ISSUE TITLE
Subscribing to a public calendar

### ISSUE THREAD

**Issue by hornse** [libasys/calendarplus#93]
englisch Version:
Hi there and thanks a lot for this app!!!
Nearly everything is working fine, I´ve got only one little problem and I don´t know how to fix it.
At the moment I could not subscribe to a public calendar. It is possible to view the web view/version of the public calendar but if I try to subscribe to this public calendar I only get an error message that my server isn´t reachable….
So I fixed the wrong URL of the generated link: webcal://owncloud/index.php/apps/calendarplus/s/eXXg86H784m6i85&webcal  
to the right one:
webcal://hornse.de/owncloud/index.php/apps/calendarplus/s/eXXg86H784m6i85&webcal

But then he´s telling me that the loaded dates are invalid.

Hopefully you´ve got an idea to fix this problem.

With kind regards

Sebastian

Deutsche Version:
Hallo und danke für die Entwicklung dieser tollen Erweiterung!
Vorsichtshalber das ganze nochmal auf deutsch, da es mit einfacher fällt mein Problem besser zu beschreiben.
Ich habe eine öffentlichen Kalender erstellt und mit Daten gefüllt. Die Webansicht dieses Kalender kann von jedem der den Link hat angeschaut werden! Versucht man jetzt diesen Kalender zu abonnieren, kommt es zu Problemen.
1. es wird ein falscher Link erzeugt:
   webcal://owncloud/index.php/apps/calendarplus/s/eXXg86H784m6i85&webcal 
   der Link müsste allerdings wie folgt aussehen:
   webcal://hornse.de/owncloud/index.php/apps/calendarplus/s/eXXg86H784m6i85&webcal

2.Der Kalender lässt sich aber auch dann nicht abonnieren, da die geladenen laut ical Daten ungültig sind.

Ich hoffe du/ ihr habt eine Lösung für dieses Problem und könnt helfen. Nochmals vielen vielen Dank für eure Arbeit

Sebastian

**Comment by hitam4450** [comment]
Hi, I would like to subscribe to a public calendar:
e.g. https://www.google.com/calendar/ical/e16qn1if96osrh1beksfks6rc0%40group.calendar.google.com/public/basic.ics  and it should be updated periodically!  How to do ??

Thanks & regards, hitam4450

**Comment by libasys** [comment]
fixed with current master (1.0.4)!
