### ISSUE TITLE
Suggestion: Do not show shared calendar as "User's calendar x" 

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#95]
When sharer shares a calendar with a sharee, the sharee sees the calendar as "Sharer's [calendarname]", while the calendarname is usually too long to be completely shown.

I would suggest to show: "[Calendarname] from sharer", as the calendarname information is more important than who shared it.

But that's just my opinion open for discussion. I might be wrong.

**Comment by MNOCFan** [comment]
I second this suggestion.

**Comment by Spheerys** [comment]
+1

**Comment by libasys** [comment]
integrated into master 1.0.5

**Comment by farson2003** [comment]
Hmm... We just updated to your 1.0.6 and it still shows Sharer's [calendarname] instead of [Calendarname] from sharer.

Maybe you need a screenshot to clarify?

**Comment by libasys** [comment]
Is clear this entry is in Database, you have to unshare, and then share again a calendar!

**Comment by farson2003** [comment]
Ok. Thx. That might be it. Good work!
