### ISSUE TITLE
Reopen: 1.0.2 - Clicking 'OK' doesn't close the dialog box.

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#96]
In fact, I just reopen this issue here: https://github.com/libasys/calendarplus/issues/91 as I can reproduce the error on my server using Calendar+ 1.02 (however I cannot reproduce it on Libasys' demo server).

Is the issue solved? and if so, when is it "rolled out" to a new update?
The app does not offer an update when the admin is logged in yet...

Thank you

**Comment by libasys** [comment]
is fixed with current master 1.0.4

**Comment by farson2003** [comment]
Thank you!
